### ISSUE TITLE
pthread 0.2.3-1 causes a libc panic with yum

### ISSUE THREAD

**Issue by tomtom-66** [bitwiseworks/pthread-os2#11]
[0047_01.TRP.txt](https://github.com/bitwiseworks/pthread-os2/files/6071660/0047_01.TRP.txt)

Continuation from https://github.com/bitwiseworks/qtwebengine-chromium-os2/issues/32#issuecomment-788194578 .

After updating pthread to 0.2.3-1,  yum crashes every time with a libc panic "fmutex deadlock: Recursive mutex!" and a trp-file is created. It is not even possible to install the debuginfo-packages you requested, and neither does (for example) "yum downgrade pthread" work. Only after succeeding in downgrading pthread to 0.2.2-1 (not in an officially approved way) did yum again work normally.

Starting situation is with libc 0.1.6-1 , libcx 0.6.9-2, pthread 0.2.2-1, gettext 0.19.8.1-3, rpm 4.13.0-19 and python 2.7.6-25. Debuginfo packages are installed for libc 0.1.7-1, pthread 0.2.3-1, and for the mentioned versions of the other packages (so only libc and pthread have debuginfo packages installed for their updated versions).

Executing "yum update pthread" seems to work normally and updates both pthread to 0.2.3-1 and also libc to 0.1.7-1. Then reboot. Next try to execute "yum update libcx". That proceeds normally up to the final question "Is this ok [y/N]:". Answering Y produces the line "Downloading Packages" and next the libc panic occurs and the trp-file is created.
The full libc panic is copied to the beginning of the trp-file.

**Comment by dmik** [comment]
Thank you for a detailed report! Also, bitwiseworks/libc#98 already *pays off* here because otherwise we'd only have a LIBC panic message which you copied on top of .txt, without that nice detailed stack trace in .TRP which made getting the complete program execution chain up to the crash point a minute task instead of at least several hours.

Thanks to .TRP I guess I already know what's wrong. It's Gettext (the internationalization library, INTL8.DLL in this case) that gets a non-recursive pthread mutex thinking it's a recursive one. Hence the crash. The reason why it was not seen before is #9. But it the crash is not seen by everyone (surely not by me) and the only guess I have here is that you are using some non-English (German?) locale which involves Gettext which triggers the bug.

Pthread for OS/2 was started many years ago as a "quick-n-dirty" hack of the win32 port (see #10 for details). At some stage (e4528d9) PTHREAD_MUTEX_RECURSIVE and PTHREAD_RECURSIVE_MUTEX_INITIALIZER were added but they didn't do a thing. The previous version used OS/2 mutexes directly which are always recursive. However, #9 brought real PTHREAD_MUTEX_RECURSIVE support but this also means that such a mutex now needs an explicit recursive initialization, either via `pthread_mutexattr_settype` or using PTHREAD_RECURSIVE_MUTEX_INITIALIZER. W/o that, the mutex will be truly NON-recursive (before, it never was). Chromium (and I guess other apps) uses the former which was implemented within #9 and hence all works as expected. But Gettext uses the latter which currently does nothing, resulting in a non-recursive mutex instead of a recursive one.

I will fix it within Pthread itself. As a temporary solution, please try `set LANG=C` before running yum. This should bypass Gettext translations together with the incorrect mutex usage.

**Comment by dmik** [comment]
BTW, I can easily reproduce the crash here by `set LANG=de_DE`, respectively.

**Comment by tomtom-66** [comment]
Thank YOU for your clear explanation (and all your hard work in general). 
My locale is nl_NL_EURO, so not quite German ;) (but close enough).
Your suggested workaround enabled me to execute "yum update libcx" and other yum commands without problems.
One small, not related detail: "bldlevel \usr\lib\pthr01.dll" still outputs 0.02.2 in the Revision field instead of 0.2.3.

**Comment by dmik** [comment]
Fixed by the commit above, tested locally with YUM — no panic any more. Will test more with Chromium and other apps and create a new RPM if everything is fine. Thanks for the version problem hint. Will fix that too.

Once the new RPM is available and tested by you, feel free to report here the result of your test.

**Comment by lerdmann** [comment]
Yes, the new pthread also fixed the problem for me. I was able to install it by setting "set LANG=en_en" and then running "yum update pthread". After I installed the pthread 0.2.4, I could reset to "set LANG=de_de".

**Comment by dmik** [comment]
@lerdmann thanks for reporting back.
