### ISSUE TITLE
Add PTHREAD_STACK_MIN

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/pthread-os2#6]
This is needed for e.g. V8 sources in Chromium (https://github.com/bitwiseworks/qtwebengine-chromium-os2/issues/3).

**Comment by dmik** [comment]
According to CPREF for `DosCreateThread`, the minimum stack is one page (4K) so this will be a value for this constant.

**Comment by StevenLevine** [comment]
In <bitwiseworks/pthread-os2/issues/6/631497576@github.com>, on 05/20/20
   at 07:10 AM, Dmitriy Kuminov <notifications@github.com> said:

Hi,

>According to CPREF for `DosCreateThread`, the minimum stack is one page
>(4K) so this will be a value for this constant.

This is true, but since the space allocated by DosAllocMem will be a
minimum of 64KB of address space, we might as well use this value.  IAC,
it's unlikely a QT app will survive with a 4KB stack.

Steven

-- 
----------------------------------------------------------------------
"Steven Levine" <steve53@earthlink.net>  Warp/DIY/BlueLion etc.
www.scoug.com www.arcanoae.com www.warpcave.com
----------------------------------------------------------------------

**Comment by dmik** [comment]
Hmm, interesting consideration. But this is not the default stack size and it isn't supposed to be used like that I think. The default is 0 which lets the OS select. This value is used in Chromium in a form of `if (stack > 0 && stack < PTHREAD_STACK_MIN) stack = PTHREAD_STACK_MIN`. So it's just to make sure that some theoretical minimum is used. Also, please e.g. read this:

https://lists.freebsd.org/pipermail/freebsd-current/2014-March/048885.html

Sit is supposed to be the theoretical minimum. For this reason I think it's better to leave it at 4K.

I have discovered, however, that our `pthread` library maintains an internal value PTHREAD_STACK_DEFAULT which is currently set to `2*1024*1024` (i.e. 2MB). And `pthread_create` will use this value if the pthread_attr spec is missing or the stack size is set there to something smaller.

I don't like this approach as it makes impossible to create threads with a stack smaller than 2MB. I will change the code so that PTHREAD_STACK_DEFAULT is only used if pthread_attr is not provided or if the stack size is 0 there.

JFYI, `_beginthread` in LIBC uses different numbers. There is a minimum limit as well and it's set to 4KB by default (can be changed with the LIBC_THREAD_MIN_STACK_SIZE environment variable). But 0 is also recognized and it results into a 512KB stack size. So doing what I propose will make `pthread_create` behave similarly except that the default stack size will be 2MB (I don't see a need to change that as it might break some apps).
